### ISSUE TITLE
ComputeError: Cannot convert [4] to number!

### ISSUE THREAD

**Issue by Telumire** [EvanBalster/TiddlyWikiFormula#32] opened 2021-09-21 13:13 UTC
The following formula return the error "ComputeError: Cannot convert "4" to number!" : 

`(= let(nb = [[1]add[3]] ): (value(nb)*2) =)`

Is that a bug or am I doing something wrong ?

**Comment by EvanBalster** [comment] 2021-09-22 20:13
Currently, the formulas plugin treats filter outputs as arrays and won't automatically convert a single-value array to a number.

In this case, you could solve the problem by wrapping your filter expression with the `first` or `last` function:
```
(= let(nb = first([[1]add[3]]) ): (value(nb)*2) =)
```
...or by using the + operator rather than filters for math...
```
(= let(nb = 1+3 ): (value(nb)*2) =)
```

**Comment by Telumire** [comment] 2021-09-27 09:57
I see, thanks !

**Comment by EvanBalster** [comment] 2021-09-29 18:45
I think it's valid to expect the plugin to automatically convert single-element arrays, so I'm inclined to keep this issue open.

**Comment by EvanBalster** [comment] 2021-09-29 18:46
On second thought this is a duplicate of https://github.com/EvanBalster/TiddlyWikiFormula/issues/30.

**Closed as completed by EvanBalster** 2021-09-29 18:46 UTC
Labels: duplicate, enhancement
